#!usr/bin/env php
<?php

define('ROOT_PATH', __DIR__);
define('DS', DIRECTORY_SEPARATOR);
define('VERSION', '1.0.0');
require __DIR__.'/vendor/autoload.php';

use App\Console\Console;
use Symfony\Component\Console\Application as SymfonyApplication;

// While in blindmode (Artisan Console) we don't need the real public path,
// but will overwrite the PUBLIC_PATH value with the root path.
define('APP_PATH', ROOT_PATH . DS . 'app');
define('CONFIG_PATH', ROOT_PATH . DS . 'config');
define('STORAGE_PATH', ROOT_PATH . DS . 'storage');
define('DATABASE_PATH', ROOT_PATH . DS . 'storage/database/');
define('CONTENT_PATH', ROOT_PATH . DS . 'content');
define('ROUTES_PATH', ROOT_PATH . DS . 'routes');
define('VIEWS_PATH', APP_PATH . DS . 'Views');
define('PUBLIC_PATH', ROOT_PATH);
define('VENDOR_PATH', ROOT_PATH . DS . 'vendor');

/**
 * Initialize the Application with the current setup
 */
$app = App\Application::instance();
$app->headless();

// Set default time based on location input
date_default_timezone_set(config()->get('app.timezone')); 

$console = new Console(new SymfonyApplication("👋 Running WikiPeep version " . VERSION), null);
$console->run();